# Generated by Django 3.1 on 2020-09-07 15:49

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import scraping.models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', jsonfield.fields.JSONField(default=dict, verbose_name='Данные ошибки')),
                ('timestamp', models.DateField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Ошибка',
                'verbose_name_plural': 'Ошибки',
            },
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_in_json', jsonfield.fields.JSONField(default=scraping.models.default_url, verbose_name='Адрес')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'URL-Адрес',
                'verbose_name_plural': 'URL-Адреса',
            },
        ),
        migrations.DeleteModel(
            name='ErrorLog',
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'Специальность', 'verbose_name_plural': 'Специальности'},
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='url',
            new_name='url_field',
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.language', verbose_name='Специальность'),
        ),
        migrations.DeleteModel(
            name='UrlAddress',
        ),
        migrations.AddField(
            model_name='url',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.language', verbose_name='Специальность'),
        ),
        migrations.AlterUniqueTogether(
            name='url',
            unique_together={('city', 'language')},
        ),
    ]
