# Generated by Django 3.1.1 on 2020-09-27 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200927_2343'),
        ('scraping', '0003_auto_20200927_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scraping.location', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scraping.specialty', verbose_name='Язык программирования'),
        ),
    ]
